baseURL: http://localhost
projectName: Swapp
scenarios:
    - path: ./benchmark/scenario1.js
      name: Consulter les titres
    - path: ./benchmark/scenario2.js
      name: Consulter un article
containers:
  - swapp-static_hosting-1